export const skills = [
  "HTML",
  "CSS",
  "JS",
  "SCSS / SASS",
  "VueJS",
  "GSAP",
  "Vuetify",
  "NuxtJS",
  "AlpineJS",
  "ES6",
  "TypeScript",
  "NodeJS",
  "NestJS",
  "GraphQL",
  "ExpressJS",
  "PrismaJS",
  "PHP",
  "Laravel",
  "MySQL",
  "MariaDB",
  "SQL Server",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Jira",
  "Postman",
  "ReactJS",
  "NextJS",
];

export const socialMediaLinks: SMLink[] = [
  {
    name: "Github",
    url: "https://github.com/mehdijai",
    logo: "/icons/github.svg",
  },
  {
    name: "LinkedIn",
    url: "https://linkedin.com/mehdijai",
    logo: "/icons/linkedin.svg",
  },
];
